USE GD1C2026;
GO

DROP TABLE IF EXISTS TP_APROBADO.Detalle_Venta_Vuelo;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Venta_Hospedaje;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Venta_Excursion;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Propuesta_Vuelo;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Propuesta_Hospedaje;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Solicitud;
DROP TABLE IF EXISTS TP_APROBADO.Detalle_Encuesta;
DROP TABLE IF EXISTS TP_APROBADO.Venta;
DROP TABLE IF EXISTS TP_APROBADO.Propuesta;
DROP TABLE IF EXISTS TP_APROBADO.Solicitud;
DROP TABLE IF EXISTS TP_APROBADO.Habitacion;
DROP TABLE IF EXISTS TP_APROBADO.Hospedaje;
DROP TABLE IF EXISTS TP_APROBADO.Vuelo;
DROP TABLE IF EXISTS TP_APROBADO.Agente;
DROP TABLE IF EXISTS TP_APROBADO.Excursion;
DROP TABLE IF EXISTS TP_APROBADO.Encuesta;
DROP TABLE IF EXISTS TP_APROBADO.Cliente;
DROP TABLE IF EXISTS TP_APROBADO.Aerolinea;
DROP TABLE IF EXISTS TP_APROBADO.Aeropuerto;
DROP TABLE IF EXISTS TP_APROBADO.Agencia;
DROP TABLE IF EXISTS TP_APROBADO.Ciudad;
DROP TABLE IF EXISTS TP_APROBADO.Proveedor;
DROP TABLE IF EXISTS TP_APROBADO.Pais;
DROP TABLE IF EXISTS TP_APROBADO.Localidad;
DROP TABLE IF EXISTS TP_APROBADO.Provincia;
DROP TABLE IF EXISTS TP_APROBADO.Estado;
DROP TABLE IF EXISTS TP_APROBADO.Medio_Pago;
DROP TABLE IF EXISTS TP_APROBADO.Canal_Venta;
DROP TABLE IF EXISTS TP_APROBADO.Aspecto;
DROP TABLE IF EXISTS TP_APROBADO.Alianza;
GO